//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetDNS.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetDNS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 DNS successfully set. 的本地化字符串。
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_DNS_successfully_set_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_DNS_successfully_set_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DNS successfully set. Reboot is required. 的本地化字符串。
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_DNS_successfully_set__Reboot_is_required_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_DNS_successfully_set__Reboot_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting DNS failed. 的本地化字符串。
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_Setting_DNS_failed_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_Setting_DNS_failed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting DNS failed with error code: 的本地化字符串。
        /// </summary>
        internal static string DNSChangerForm_btnSave_Click_Setting_DNS_failed_with_error_code_ {
            get {
                return ResourceManager.GetString("DNSChangerForm_btnSave_Click_Setting_DNS_failed_with_error_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        internal static string DNSChangerForm_DNSChangerForm_Manual {
            get {
                return ResourceManager.GetString("DNSChangerForm_DNSChangerForm_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress: {0:0.0}%
        ///Download speed: {1:0.0} KB/s
        ///File size: {2:n0} / {3:n0} KB 的本地化字符串。
        /// </summary>
        internal static string DownloaderForm_ChangeProgress_Progress {
            get {
                return ResourceManager.GetString("DownloaderForm_ChangeProgress_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status: {0} 的本地化字符串。
        /// </summary>
        internal static string DownloaderForm_ChangeStatus_Status___0_ {
            get {
                return ResourceManager.GetString("DownloaderForm_ChangeStatus_Status___0_", resourceCulture);
            }
        }
    }
}
